import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent } from '@/components/ui/card';
import {
  ArrowRight,
  Github,
  GitPullRequest,
  Clock3,
  AlertCircle,
  Settings
} from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, XAxis, CartesianGrid } from 'recharts';
import { Badge } from '@/components/ui/badge';
import { useRepository } from '@/contexts/RepositoryContext';
import { apiClient } from '@/lib/api-client';
import type { AnalyticsCardMetric } from '@/types/api';

const miniChartData = [
  { name: 'Mon', value: 12 },
  { name: 'Tue', value: 18 },
  { name: 'Wed', value: 15 },
  { name: 'Thu', value: 25 },
  { name: 'Fri', value: 20 },
  { name: 'Sat', value: 32 },
  { name: 'Sun', value: 28 },
];

export const DashboardPage: React.FC = () => {
  const navigate = useNavigate();
  const { selectedRepo } = useRepository();
  const [cards, setCards] = useState<AnalyticsCardMetric[]>([]);
  const [loadingCards, setLoadingCards] = useState(false);
  const [cardsError, setCardsError] = useState<string | null>(null);

  useEffect(() => {
    const fetchDashboardCards = async () => {
      if (!selectedRepo?.repository) {
        setCards([]);
        setCardsError(null);
        return;
      }

      setLoadingCards(true);
      setCardsError(null);
      try {
        const response = await apiClient.getDashboardAnalytics(selectedRepo.repository);
        setCards(response.cards);
      } catch (error) {
        setCardsError(error instanceof Error ? error.message : 'Failed to load dashboard analytics');
      } finally {
        setLoadingCards(false);
      }
    };

    fetchDashboardCards();
  }, [selectedRepo?.repository]);

  const cardMap = useMemo(() => {
    return new Map(cards.map((card) => [card.key, card]));
  }, [cards]);

  return (
    <div className="space-y-4 pt-4 max-w-6xl mx-auto flex flex-col md:h-full">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 shrink-0">
        <div>
          <h1 className="landing-display text-3xl font-black">Dashboard</h1>
          <div className="mt-1 flex items-center gap-2">
            <p className="text-black/60 text-sm font-bold">Repository:</p>
            <Badge
              variant="neutral"
              className="border-2 border-black bg-[var(--metis-pastel-2)] px-2 py-0.5 text-sm font-black shadow-[2px_2px_0px_0px_#000]"
            >
              {selectedRepo?.repository || 'No repository selected'}
            </Badge>
          </div>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid gap-4 md:grid-cols-3 shrink-0">
        <Card className="border-2 border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-black/60 text-xs font-bold">PRs Reviewed</p>
              <GitPullRequest className="h-4 w-4 text-black/50" />
            </div>
            <p className="mt-1 text-2xl font-black">
              {loadingCards ? '...' : (cardMap.get('prs_reviewed')?.display_value ?? '--')}
            </p>
            <p className="mt-1 text-[11px] leading-tight text-black/55">
              {cardMap.get('prs_reviewed')?.description ?? 'Distinct pull requests reviewed.'}
            </p>
          </CardContent>
        </Card>
        <Card className="border-2 border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-black/60 text-xs font-bold">Issues Detected</p>
              <AlertCircle className="h-4 w-4 text-black/50" />
            </div>
            <p className="mt-1 text-2xl font-black">
              {loadingCards ? '...' : (cardMap.get('issues_detected')?.display_value ?? '--')}
            </p>
            <p className="mt-1 text-[11px] leading-tight text-black/55">
              {cardMap.get('issues_detected')?.description ?? 'AI findings generated by review runs.'}
            </p>
          </CardContent>
        </Card>
        <Card className="border-2 border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-black/60 text-xs font-bold">Review Latency</p>
              <Clock3 className="h-4 w-4 text-black/50" />
            </div>
            <p className="mt-1 text-2xl font-black">
              {loadingCards ? '...' : (cardMap.get('avg_review_latency_seconds')?.display_value ?? '--')}
            </p>
            <p className="mt-1 text-[11px] leading-tight text-black/55">
              {cardMap.get('avg_review_latency_seconds')?.description ?? 'Average review latency.'}
            </p>
          </CardContent>
        </Card>
      </div>
      {cardsError && (
        <p className="text-sm font-bold text-[var(--metis-red)]">
          Failed to load dashboard metrics: {cardsError}
        </p>
      )}

      {/* Explore Section */}
      <div className="flex flex-col md:flex-1 md:min-h-0">
        <h2 className="landing-display mb-4 text-xl font-black shrink-0">Quick Actions</h2>
        <div className="grid gap-4 md:grid-cols-2 md:flex-1 md:min-h-0">
          {/* AI Review Settings Card */}
          <Card
            className="group flex cursor-pointer flex-col border-2 border-black bg-white transition-all hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_var(--metis-orange-dark)]"
            onClick={() => navigate('/dashboard/ai-review')}
          >
            <CardContent className="flex flex-1 flex-col p-4">
              <div className="relative mb-2 flex h-32 w-full md:h-24 md:flex-1 flex-col overflow-hidden rounded border-2 border-black bg-[#1e1e1e] p-0">
                <div className="flex items-center justify-between border-b border-[#404040] bg-[#2d2d2d] px-3 py-2">
                  <span className="font-mono text-[10px] text-white/60">src/auth/validator.ts</span>
                  <div className="flex gap-1">
                    <div className="h-2 w-2 rounded-full bg-red-500"></div>
                    <div className="h-2 w-2 rounded-full bg-yellow-500"></div>
                    <div className="h-2 w-2 rounded-full bg-green-500"></div>
                  </div>
                </div>
                <div className="p-2 font-mono text-[10px] leading-relaxed text-white/70">
                  <div className="flex">
                    <span className="w-4 text-white/30 select-none">12</span>
                    <span>
                      <span className="text-purple-400">const</span>{' '}
                      <span className="text-blue-400">isValid</span> = (p) ={'>'} {'{'}
                    </span>
                  </div>
                  <div className="flex w-full bg-red-900/30">
                    <span className="w-4 text-white/30 select-none">13</span>
                    <span className="text-red-400">- if (p.length {'<'} 6) return;</span>
                  </div>
                  <div className="flex w-full bg-green-900/30">
                    <span className="w-4 text-white/30 select-none">13</span>
                    <span className="text-green-400">+ if (p.length {'<'} 8) return;</span>
                  </div>
                </div>

                <div className="absolute right-2 bottom-2">
                  <Badge
                    variant="neutral"
                    className="border-2 border-black bg-white text-[10px] font-bold text-[var(--metis-red)] shadow-[2px_2px_0px_0px_#000]"
                  >
                    AI Fix
                  </Badge>
                </div>
              </div>
              <h3 className="mb-1 flex items-center gap-2 text-base font-black">
                AI Review Settings
                <ArrowRight className="h-3 w-3 opacity-0 transition-opacity group-hover:opacity-100" />
              </h3>
              <p className="text-black/60 text-xs">
                Configure sensitivity, ignore patterns, and custom instructions.
              </p>
            </CardContent>
          </Card>

          {/* Issues Card */}
          <Card
            className="group flex cursor-pointer flex-col border-2 border-black bg-white transition-all hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_var(--metis-red)]"
            onClick={() => navigate('/dashboard/issues')}
          >
            <CardContent className="flex flex-1 flex-col p-4">
              <div className="relative mb-2 flex h-32 w-full md:h-24 md:flex-1 flex-col items-center justify-center gap-2 overflow-hidden rounded border-2 border-black bg-[var(--metis-pastel-red)]">
                <div className="absolute inset-0 bg-[radial-gradient(var(--metis-red)_1px,transparent_1px)] [background-size:12px_12px] opacity-25"></div>
                <Github className="z-10 h-10 w-10 text-black" />
                <div className="z-10 flex items-center gap-2 rounded border-2 border-black bg-[var(--metis-red)] px-3 py-1 text-xs font-black shadow-[2px_2px_0px_0px_#000]">
                  <span className="text-white">Launch AI Agents</span>
                </div>
              </div>
              <h3 className="mb-1 flex items-center gap-2 text-base font-black">
                Manage Issues
                <ArrowRight className="h-3 w-3 opacity-0 transition-opacity group-hover:opacity-100" />
              </h3>
              <p className="text-black/60 text-xs">
                View GitHub issues and launch AI agents to solve them automatically.
              </p>
            </CardContent>
          </Card>

          {/* Analytics Card */}
          <Card
            className="group flex cursor-pointer flex-col border-2 border-black bg-white transition-all hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_var(--metis-yellow)]"
            onClick={() => navigate('/dashboard/analytics')}
          >
            <CardContent className="flex flex-1 flex-col p-4">
              <div className="relative mb-2 h-32 w-full md:h-24 md:flex-1 overflow-hidden rounded border-2 border-black bg-white p-2">
                <div className="absolute inset-0 pt-4 pr-2">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={miniChartData}>
                      <defs>
                        <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="var(--metis-orange-light)" stopOpacity={0.8} />
                          <stop offset="95%" stopColor="var(--metis-orange-light)" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(0,0,0,0.1)" />
                      <XAxis dataKey="name" hide />
                      <Area
                        type="monotone"
                        dataKey="value"
                        stroke="#000"
                        strokeWidth={3}
                        fillOpacity={1}
                        fill="url(#colorValue)"
                      />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              </div>
              <h3 className="mb-1 flex items-center gap-2 text-base font-black">
                Analytics
                <ArrowRight className="h-3 w-3 opacity-0 transition-opacity group-hover:opacity-100" />
              </h3>
              <p className="text-black/60 text-xs">
                Deep dive into your team's velocity and code quality metrics.
              </p>
            </CardContent>
          </Card>

          {/* Manage Repos Card */}
          <Card
            className="group flex cursor-pointer flex-col border-2 border-black bg-white transition-all hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_var(--metis-orange-dark)]"
            onClick={() => navigate('/dashboard/repositories')}
          >
            <CardContent className="flex flex-1 flex-col p-4">
              <div className="relative mb-2 flex h-32 w-full md:h-24 md:flex-1 flex-col items-center justify-center gap-2 overflow-hidden rounded border-2 border-black bg-[var(--metis-pastel-4)]">
                <div className="absolute inset-0 bg-[radial-gradient(var(--metis-orange-dark)_1px,transparent_1px)] [background-size:12px_12px] opacity-20"></div>
                <Settings className="z-10 h-10 w-10 text-[var(--metis-orange-dark)]" />
                <div className="z-10 flex items-center gap-2 rounded border-2 border-black bg-[var(--metis-orange-dark)] px-3 py-1 text-xs font-black shadow-[2px_2px_0px_0px_#000]">
                  <span className="text-white">Configure Repos</span>
                </div>
              </div>
              <h3 className="mb-1 flex items-center gap-2 text-base font-black">
                Manage Repositories
                <ArrowRight className="h-3 w-3 opacity-0 transition-opacity group-hover:opacity-100" />
              </h3>
              <p className="text-black/60 text-xs">
                Add new repositories, configure settings, and manage integrations.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};
