"""Fix: Change github_installation_id unique constraint to composite with repository

Revision ID: 670b7ce006e1
Revises: 9308de41b8f0
Create Date: 2025-12-14 18:58:49.581406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "670b7ce006e1"
down_revision: Union[str, Sequence[str], None] = "9308de41b8f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_installations_github_installation_id"), table_name="installations")
    op.create_index(
        op.f("ix_installations_github_installation_id"),
        "installations",
        ["github_installation_id"],
        unique=False,
    )
    op.create_index(
        "ix_installations_github_installation_id_repository",
        "installations",
        ["github_installation_id", "repository"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_installations_github_installation_id_repository", table_name="installations")
    op.drop_index(op.f("ix_installations_github_installation_id"), table_name="installations")
    op.create_index(
        op.f("ix_installations_github_installation_id"),
        "installations",
        ["github_installation_id"],
        unique=True,
    )
    # ### end Alembic commands ###
