"""Add celery_task_id to reviews

Revision ID: 9308de41b8f0
Revises: e046b977f8a9
Create Date: 2025-12-14 15:06:13.077431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9308de41b8f0"
down_revision: Union[str, Sequence[str], None] = "e046b977f8a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column(
            "celery_task_id",
            sa.String(length=255),
            nullable=True,
            comment="Celery task ID for tracking",
        ),
    )
    op.create_index(op.f("ix_reviews_celery_task_id"), "reviews", ["celery_task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_celery_task_id"), table_name="reviews")
    op.drop_column("reviews", "celery_task_id")
    # ### end Alembic commands ###
