"""add review_comment title and make github_comment_id bigint

Revision ID: 113096f34455
Revises: 670b7ce006e1
Create Date: 2026-02-08 01:03:27.916621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "113096f34455"
down_revision: Union[str, Sequence[str], None] = "670b7ce006e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_comments",
        sa.Column(
            "title", sa.String(length=255), nullable=True, comment="Short finding title"
        ),
    )
    op.alter_column(
        "review_comments",
        "github_comment_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment="GitHub API comment ID (bigint)",
        existing_comment="GitHub API comment ID",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_comments",
        "github_comment_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment="GitHub API comment ID",
        existing_comment="GitHub API comment ID (bigint)",
        existing_nullable=True,
    )
    op.drop_column("review_comments", "title")
    # ### end Alembic commands ###
